#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           RightMotor,    tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**************************************************
 * STRUCTS AND EUMS
 **************************************************/

typedef struct vector_2_float
{
	float x, y;
} Vector2f;

/**************************************************
 * FUNCTIONS
 **************************************************/

void MoveRobot()
{
	/*********************************************************************
	 * Two Vectors, One for Forward, the Other for turning
	 * if we move the joystick to the right, then we want to turn right,
	 * so we need to slow down the right motor in order to turn right,
	 * and keep the left motor the same speed
	 * and vice versa if we want to go left
	 *********************************************************************/

	// two dimensional vector for movement
	Vector2f vec;
	vec.x = vexRT[Ch1];
	vec.y = vexRT[Ch2];

	// two variables for each motor
	float left_speed = vec.y;
	float right_speed = -vec.y;

	// Slow Down one motor if x axis has input
	if (vec.x < 0)
		right_speed -= vec.x;
	else if( vec.x > 0)
		left_speed -= vec.x;

	// if y axis doesn't have input but the x axis does then spin
	if ((int)vec.y == 0 && vec.x < 0 || vec.x > 0)
	{
		left_speed = vec.x;
		right_speed = vec.x;
	}

	// set the speed of the motor individually
	motor[LeftMotor] = left_speed;
	motor[RightMotor] = right_speed;
}

task main()
{

	while (true)
	{
		MoveRobot();
	}

}
