#pragma config(Sensor, dgtl1,  FrontInput,     sensorSONAR_inch)
#pragma config(Sensor, dgtl3,  LeftInput,      sensorSONAR_inch)
#pragma config(Sensor, dgtl5,  RightInput,     sensorSONAR_inch)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           RightMotor,    tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**************************************************
 * STRUCTS AND EUMS
 **************************************************/

typedef struct vector_2_float
{
	float x, y;
} Vector2f;

typedef struct robot
{
	int left_speed;
	int right_speed;
	Vector2f dir_vec;
} Robot;

/**************************************************
 * GLOBALS
 **************************************************/

Robot rbot;

/**************************************************
 * FUNCTIONS
 **************************************************/

void init_robot()
{
	rbot.left_speed = 127;
	rbot.right_speed = 127;
	rbot.dir_vec.x = 0;
	rbot.dir_vec.y = 0;
}

void figure_out_location()
{
	// Vertical Vector
	if (SensorValue[FrontInput] < 12)
		rbot.dir_vec.y = 0;
	else
		rbot.dir_vec.y = 127;

	// Horizontal Vector
	if (SensorValue[LeftInput] < 12 || SensorValue[RightInput] < 12)
		rbot.dir_vec.x = (SensorValue[LeftInput] < 12 ? -127 : 127);
	else
		rbot.dir_vec.x = 0;
	
}

void move_robot()
{
	rbot.dir_vec.x = 0;
	rbot.dir_vec.y = 127;

	figure_out_location();	

	// Slow Down one motor if x axis has input
	if (rbot.dir_vec.x < 0)
		rbot.right_speed -= rbot.dir_vec.x;
	else if(rbot.dir_vec.x > 0)
		rbot.left_speed += rbot.dir_vec.x;

	// if y axis doesn't have input but the x axis does then spin
	if ((int)rbot.dir_vec.y == 0 && (int)rbot.dir_vec.x < 0 || (int)rbot.dir_vec.x > 0)
	{
		rbot.left_speed = rbot.dir_vec.y;
		rbot.right_speed = rbot.dir_vec.y;
	}

	motor[LeftMotor] = rbot.left_speed;
	motor[RightMotor] = rbot.right_speed;
}

task main()
{
	init_robot();

	while (true)
	{
		move_robot();
	}

}
