#pragma config(Sensor, in1,    Lighty,         sensorReflection)
#pragma config(Sensor, dgtl1,  Bumpy,          sensorDigitalIn)
#pragma config(Motor,  port2,           Thwacker,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           Movvy,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           Flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TIME_WAIT 2000
#define MOVVY_SPEED 30
#define TIME_SLASH 160
#define QUEUE_SIZE 100

/*********************************
 * Structures And Enumerations
*********************************/

typedef enum marble_type
{
	NONE = -1,
	CLEAR = 0,
	WOOD = 1,
	METAL = 2
} MarbleType;

typedef struct range
{
	int min;
	int max;
} LightRange;

/*********************************
 * Global Variables
*********************************/

LightRange ranges[3];

/*********************************
 * Functions
*********************************/

MarbleType GetMarbleType()
{
	delay(1000);

	if (SensorValue[Lighty] < ranges[CLEAR].max && SensorValue[Lighty] > ranges[CLEAR].min)
		return CLEAR;

	if (SensorValue[Lighty] < ranges[METAL].max && SensorValue[Lighty] > ranges[METAL].min)
		return METAL;

	if (SensorValue[Lighty] < ranges[WOOD].max && SensorValue[Lighty] > ranges[WOOD].min)
		return WOOD;

 	return NONE;
}

void MovementOfTheThwacker(int speed, int pos)
{
	motor[Movvy] = -speed;
	delay(TIME_WAIT / TIME_SLASH);
	motor[Thwacker] = pos;
	delay(TIME_WAIT / TIME_SLASH);
	motor[Movvy] = 0;
}

void MoveThwacker(MarbleType type)
{
	switch (type)
	{
		case CLEAR:
			MovementOfTheThwacker(MOVVY_SPEED, 0);
			break;
		case WOOD:
			MovementOfTheThwacker(MOVVY_SPEED, -180);
			break;
		case METAL:
			MovementOfTheThwacker(MOVVY_SPEED, 180);
			break;
		default:

	}

	delay(TIME_WAIT);
	motor[Thwacker] = 0;
}

void SetUpRanges(MarbleType type, int min, int max)
{
	ranges[type].min = min;
	ranges[type].max = max;
}

/*********************************vvvvvvvvvvvvvvv
 * Tasks
*********************************/

task main()
{
	SetUpRanges(CLEAR, 0, 300);
	SetUpRanges(WOOD, 300, 400);
	SetUpRanges(METAL, 400, 700);

	//q.count = QUEUE_SIZE;

	while (true)
	{
		MoveThwacker(GetMarbleType());
	}

}
